[package]
name = "pgmt_cli"
version = "0.0.0"
edition = "2024"

[dependencies]
clap = { workspace = true }
pgmt_core = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
pretty_assertions = { workspace = true }
