[package]
name = "pgmt_macros"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
pgmt_core = { workspace = true }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
